[general]
library_name = "libiceoryx2_ffi_c"
output_file_path = "../src/generated/Iceoryx2FFI.jl"
module_name = "Iceoryx2FFI"
jll_pkg_name = "Iceoryx2_jll"
use_julia_native_enum_type = false
auto_mutability = false
extract_c_comment_style = "doxygen"
show_c_function_prototype = true
use_deterministic_symbol = true
smart_de_anonymize = true
export_symbol_prefixes = ["iox2_", "IOX2_"]

[codegen]
use_julia_bool = true
use_ccall_macro = true
always_NUL_terminated_string = true
opaque_as_mutable_struct = false

[codegen.macro]
macro_mode = "basic"
