# This file is autogenerated by gen/gen-bindings.jl from src/Iceoryx2FFI.jl. Do not edit by hand.

const _IOX2_OK = Iceoryx2FFI.IOX2_OK

@noinline function _error_message(::Type{Iceoryx2FFI.iox2_attribute_definition_error_e}, code::Iceoryx2FFI.iox2_attribute_definition_error_e)
    return string(code)
end

@noinline function _error_message(::Type{Iceoryx2FFI.iox2_attribute_verification_error_e}, code::Iceoryx2FFI.iox2_attribute_verification_error_e)
    return string(code)
end

@noinline function _error_message(::Type{Iceoryx2FFI.iox2_blackboard_create_error_e}, code::Iceoryx2FFI.iox2_blackboard_create_error_e)
    ptr = Iceoryx2FFI.iox2_blackboard_create_error_string(code)
    return unsafe_string(ptr)
end

@noinline function _error_message(::Type{Iceoryx2FFI.iox2_blackboard_open_error_e}, code::Iceoryx2FFI.iox2_blackboard_open_error_e)
    ptr = Iceoryx2FFI.iox2_blackboard_open_error_string(code)
    return unsafe_string(ptr)
end

@noinline function _error_message(::Type{Iceoryx2FFI.iox2_client_create_error_e}, code::Iceoryx2FFI.iox2_client_create_error_e)
    ptr = Iceoryx2FFI.iox2_client_create_error_string(code)
    return unsafe_string(ptr)
end

@noinline function _error_message(::Type{Iceoryx2FFI.iox2_config_creation_error_e}, code::Iceoryx2FFI.iox2_config_creation_error_e)
    ptr = Iceoryx2FFI.iox2_config_creation_error_string(code)
    return unsafe_string(ptr)
end

@noinline function _error_message(::Type{Iceoryx2FFI.iox2_connection_failure_e}, code::Iceoryx2FFI.iox2_connection_failure_e)
    ptr = Iceoryx2FFI.iox2_connection_failure_string(code)
    return unsafe_string(ptr)
end

@noinline function _error_message(::Type{Iceoryx2FFI.iox2_entry_handle_error_e}, code::Iceoryx2FFI.iox2_entry_handle_error_e)
    ptr = Iceoryx2FFI.iox2_entry_handle_error_string(code)
    return unsafe_string(ptr)
end

@noinline function _error_message(::Type{Iceoryx2FFI.iox2_entry_handle_mut_error_e}, code::Iceoryx2FFI.iox2_entry_handle_mut_error_e)
    ptr = Iceoryx2FFI.iox2_entry_handle_mut_error_string(code)
    return unsafe_string(ptr)
end

@noinline function _error_message(::Type{Iceoryx2FFI.iox2_event_open_or_create_error_e}, code::Iceoryx2FFI.iox2_event_open_or_create_error_e)
    ptr = Iceoryx2FFI.iox2_event_open_or_create_error_string(code)
    return unsafe_string(ptr)
end

@noinline function _error_message(::Type{Iceoryx2FFI.iox2_listener_create_error_e}, code::Iceoryx2FFI.iox2_listener_create_error_e)
    ptr = Iceoryx2FFI.iox2_listener_create_error_string(code)
    return unsafe_string(ptr)
end

@noinline function _error_message(::Type{Iceoryx2FFI.iox2_listener_wait_error_e}, code::Iceoryx2FFI.iox2_listener_wait_error_e)
    ptr = Iceoryx2FFI.iox2_listener_wait_error_string(code)
    return unsafe_string(ptr)
end

@noinline function _error_message(::Type{Iceoryx2FFI.iox2_loan_error_e}, code::Iceoryx2FFI.iox2_loan_error_e)
    ptr = Iceoryx2FFI.iox2_loan_error_string(code)
    return unsafe_string(ptr)
end

@noinline function _error_message(::Type{Iceoryx2FFI.iox2_node_cleanup_failure_e}, code::Iceoryx2FFI.iox2_node_cleanup_failure_e)
    return string(code)
end

@noinline function _error_message(::Type{Iceoryx2FFI.iox2_node_creation_failure_e}, code::Iceoryx2FFI.iox2_node_creation_failure_e)
    ptr = Iceoryx2FFI.iox2_node_creation_failure_string(code)
    return unsafe_string(ptr)
end

@noinline function _error_message(::Type{Iceoryx2FFI.iox2_node_list_failure_e}, code::Iceoryx2FFI.iox2_node_list_failure_e)
    ptr = Iceoryx2FFI.iox2_node_list_failure_string(code)
    return unsafe_string(ptr)
end

@noinline function _error_message(::Type{Iceoryx2FFI.iox2_node_wait_failure_e}, code::Iceoryx2FFI.iox2_node_wait_failure_e)
    ptr = Iceoryx2FFI.iox2_node_wait_failure_string(code)
    return unsafe_string(ptr)
end

@noinline function _error_message(::Type{Iceoryx2FFI.iox2_notifier_create_error_e}, code::Iceoryx2FFI.iox2_notifier_create_error_e)
    ptr = Iceoryx2FFI.iox2_notifier_create_error_string(code)
    return unsafe_string(ptr)
end

@noinline function _error_message(::Type{Iceoryx2FFI.iox2_notifier_notify_error_e}, code::Iceoryx2FFI.iox2_notifier_notify_error_e)
    ptr = Iceoryx2FFI.iox2_notifier_notify_error_string(code)
    return unsafe_string(ptr)
end

@noinline function _error_message(::Type{Iceoryx2FFI.iox2_pub_sub_open_or_create_error_e}, code::Iceoryx2FFI.iox2_pub_sub_open_or_create_error_e)
    ptr = Iceoryx2FFI.iox2_pub_sub_open_or_create_error_string(code)
    return unsafe_string(ptr)
end

@noinline function _error_message(::Type{Iceoryx2FFI.iox2_publisher_create_error_e}, code::Iceoryx2FFI.iox2_publisher_create_error_e)
    ptr = Iceoryx2FFI.iox2_publisher_create_error_string(code)
    return unsafe_string(ptr)
end

@noinline function _error_message(::Type{Iceoryx2FFI.iox2_reader_create_error_e}, code::Iceoryx2FFI.iox2_reader_create_error_e)
    ptr = Iceoryx2FFI.iox2_reader_create_error_string(code)
    return unsafe_string(ptr)
end

@noinline function _error_message(::Type{Iceoryx2FFI.iox2_receive_error_e}, code::Iceoryx2FFI.iox2_receive_error_e)
    ptr = Iceoryx2FFI.iox2_receive_error_string(code)
    return unsafe_string(ptr)
end

@noinline function _error_message(::Type{Iceoryx2FFI.iox2_request_response_open_or_create_error_e}, code::Iceoryx2FFI.iox2_request_response_open_or_create_error_e)
    ptr = Iceoryx2FFI.iox2_request_response_open_or_create_error_string(code)
    return unsafe_string(ptr)
end

@noinline function _error_message(::Type{Iceoryx2FFI.iox2_request_send_error_e}, code::Iceoryx2FFI.iox2_request_send_error_e)
    ptr = Iceoryx2FFI.iox2_request_send_error_string(code)
    return unsafe_string(ptr)
end

@noinline function _error_message(::Type{Iceoryx2FFI.iox2_semantic_string_error_e}, code::Iceoryx2FFI.iox2_semantic_string_error_e)
    ptr = Iceoryx2FFI.iox2_semantic_string_error_string(code)
    return unsafe_string(ptr)
end

@noinline function _error_message(::Type{Iceoryx2FFI.iox2_send_error_e}, code::Iceoryx2FFI.iox2_send_error_e)
    ptr = Iceoryx2FFI.iox2_send_error_string(code)
    return unsafe_string(ptr)
end

@noinline function _error_message(::Type{Iceoryx2FFI.iox2_server_create_error_e}, code::Iceoryx2FFI.iox2_server_create_error_e)
    ptr = Iceoryx2FFI.iox2_server_create_error_string(code)
    return unsafe_string(ptr)
end

@noinline function _error_message(::Type{Iceoryx2FFI.iox2_service_details_error_e}, code::Iceoryx2FFI.iox2_service_details_error_e)
    ptr = Iceoryx2FFI.iox2_service_details_error_string(code)
    return unsafe_string(ptr)
end

@noinline function _error_message(::Type{Iceoryx2FFI.iox2_service_list_error_e}, code::Iceoryx2FFI.iox2_service_list_error_e)
    ptr = Iceoryx2FFI.iox2_service_list_error_string(code)
    return unsafe_string(ptr)
end

@noinline function _error_message(::Type{Iceoryx2FFI.iox2_subscriber_create_error_e}, code::Iceoryx2FFI.iox2_subscriber_create_error_e)
    ptr = Iceoryx2FFI.iox2_subscriber_create_error_string(code)
    return unsafe_string(ptr)
end

@noinline function _error_message(::Type{Iceoryx2FFI.iox2_type_detail_error_e}, code::Iceoryx2FFI.iox2_type_detail_error_e)
    return string(code)
end

@noinline function _error_message(::Type{Iceoryx2FFI.iox2_waitset_attachment_error_e}, code::Iceoryx2FFI.iox2_waitset_attachment_error_e)
    ptr = Iceoryx2FFI.iox2_waitset_attachment_error_string(code)
    return unsafe_string(ptr)
end

@noinline function _error_message(::Type{Iceoryx2FFI.iox2_waitset_create_error_e}, code::Iceoryx2FFI.iox2_waitset_create_error_e)
    ptr = Iceoryx2FFI.iox2_waitset_create_error_string(code)
    return unsafe_string(ptr)
end

@noinline function _error_message(::Type{Iceoryx2FFI.iox2_waitset_run_error_e}, code::Iceoryx2FFI.iox2_waitset_run_error_e)
    ptr = Iceoryx2FFI.iox2_waitset_run_error_string(code)
    return unsafe_string(ptr)
end

@noinline function _error_message(::Type{Iceoryx2FFI.iox2_writer_create_error_e}, code::Iceoryx2FFI.iox2_writer_create_error_e)
    ptr = Iceoryx2FFI.iox2_writer_create_error_string(code)
    return unsafe_string(ptr)
end

struct AttributeDefinitionError <: Exception
    code::Iceoryx2FFI.iox2_attribute_definition_error_e
    message::String
end

@noinline function AttributeDefinitionError(code::Iceoryx2FFI.iox2_attribute_definition_error_e)
    return AttributeDefinitionError(code, _error_message(Iceoryx2FFI.iox2_attribute_definition_error_e, code))
end

function Base.showerror(io::IO, err::AttributeDefinitionError)
    print(io, "AttributeDefinitionError: ", err.message, " (", err.code, ")")
end

struct AttributeVerificationError <: Exception
    code::Iceoryx2FFI.iox2_attribute_verification_error_e
    message::String
end

@noinline function AttributeVerificationError(code::Iceoryx2FFI.iox2_attribute_verification_error_e)
    return AttributeVerificationError(code, _error_message(Iceoryx2FFI.iox2_attribute_verification_error_e, code))
end

function Base.showerror(io::IO, err::AttributeVerificationError)
    print(io, "AttributeVerificationError: ", err.message, " (", err.code, ")")
end

struct BlackboardCreateError <: Exception
    code::Iceoryx2FFI.iox2_blackboard_create_error_e
    message::String
end

@noinline function BlackboardCreateError(code::Iceoryx2FFI.iox2_blackboard_create_error_e)
    return BlackboardCreateError(code, _error_message(Iceoryx2FFI.iox2_blackboard_create_error_e, code))
end

function Base.showerror(io::IO, err::BlackboardCreateError)
    print(io, "BlackboardCreateError: ", err.message, " (", err.code, ")")
end

struct BlackboardOpenError <: Exception
    code::Iceoryx2FFI.iox2_blackboard_open_error_e
    message::String
end

@noinline function BlackboardOpenError(code::Iceoryx2FFI.iox2_blackboard_open_error_e)
    return BlackboardOpenError(code, _error_message(Iceoryx2FFI.iox2_blackboard_open_error_e, code))
end

function Base.showerror(io::IO, err::BlackboardOpenError)
    print(io, "BlackboardOpenError: ", err.message, " (", err.code, ")")
end

struct ClientCreateError <: Exception
    code::Iceoryx2FFI.iox2_client_create_error_e
    message::String
end

@noinline function ClientCreateError(code::Iceoryx2FFI.iox2_client_create_error_e)
    return ClientCreateError(code, _error_message(Iceoryx2FFI.iox2_client_create_error_e, code))
end

function Base.showerror(io::IO, err::ClientCreateError)
    print(io, "ClientCreateError: ", err.message, " (", err.code, ")")
end

struct ConfigCreationError <: Exception
    code::Iceoryx2FFI.iox2_config_creation_error_e
    message::String
end

@noinline function ConfigCreationError(code::Iceoryx2FFI.iox2_config_creation_error_e)
    return ConfigCreationError(code, _error_message(Iceoryx2FFI.iox2_config_creation_error_e, code))
end

function Base.showerror(io::IO, err::ConfigCreationError)
    print(io, "ConfigCreationError: ", err.message, " (", err.code, ")")
end

struct ConnectionFailure <: Exception
    code::Iceoryx2FFI.iox2_connection_failure_e
    message::String
end

@noinline function ConnectionFailure(code::Iceoryx2FFI.iox2_connection_failure_e)
    return ConnectionFailure(code, _error_message(Iceoryx2FFI.iox2_connection_failure_e, code))
end

function Base.showerror(io::IO, err::ConnectionFailure)
    print(io, "ConnectionFailure: ", err.message, " (", err.code, ")")
end

struct EntryHandleError <: Exception
    code::Iceoryx2FFI.iox2_entry_handle_error_e
    message::String
end

@noinline function EntryHandleError(code::Iceoryx2FFI.iox2_entry_handle_error_e)
    return EntryHandleError(code, _error_message(Iceoryx2FFI.iox2_entry_handle_error_e, code))
end

function Base.showerror(io::IO, err::EntryHandleError)
    print(io, "EntryHandleError: ", err.message, " (", err.code, ")")
end

struct EntryHandleMutError <: Exception
    code::Iceoryx2FFI.iox2_entry_handle_mut_error_e
    message::String
end

@noinline function EntryHandleMutError(code::Iceoryx2FFI.iox2_entry_handle_mut_error_e)
    return EntryHandleMutError(code, _error_message(Iceoryx2FFI.iox2_entry_handle_mut_error_e, code))
end

function Base.showerror(io::IO, err::EntryHandleMutError)
    print(io, "EntryHandleMutError: ", err.message, " (", err.code, ")")
end

struct EventOpenOrCreateError <: Exception
    code::Iceoryx2FFI.iox2_event_open_or_create_error_e
    message::String
end

@noinline function EventOpenOrCreateError(code::Iceoryx2FFI.iox2_event_open_or_create_error_e)
    return EventOpenOrCreateError(code, _error_message(Iceoryx2FFI.iox2_event_open_or_create_error_e, code))
end

function Base.showerror(io::IO, err::EventOpenOrCreateError)
    print(io, "EventOpenOrCreateError: ", err.message, " (", err.code, ")")
end

struct ListenerCreateError <: Exception
    code::Iceoryx2FFI.iox2_listener_create_error_e
    message::String
end

@noinline function ListenerCreateError(code::Iceoryx2FFI.iox2_listener_create_error_e)
    return ListenerCreateError(code, _error_message(Iceoryx2FFI.iox2_listener_create_error_e, code))
end

function Base.showerror(io::IO, err::ListenerCreateError)
    print(io, "ListenerCreateError: ", err.message, " (", err.code, ")")
end

struct ListenerWaitError <: Exception
    code::Iceoryx2FFI.iox2_listener_wait_error_e
    message::String
end

@noinline function ListenerWaitError(code::Iceoryx2FFI.iox2_listener_wait_error_e)
    return ListenerWaitError(code, _error_message(Iceoryx2FFI.iox2_listener_wait_error_e, code))
end

function Base.showerror(io::IO, err::ListenerWaitError)
    print(io, "ListenerWaitError: ", err.message, " (", err.code, ")")
end

struct LoanError <: Exception
    code::Iceoryx2FFI.iox2_loan_error_e
    message::String
end

@noinline function LoanError(code::Iceoryx2FFI.iox2_loan_error_e)
    return LoanError(code, _error_message(Iceoryx2FFI.iox2_loan_error_e, code))
end

function Base.showerror(io::IO, err::LoanError)
    print(io, "LoanError: ", err.message, " (", err.code, ")")
end

struct NodeCleanupFailure <: Exception
    code::Iceoryx2FFI.iox2_node_cleanup_failure_e
    message::String
end

@noinline function NodeCleanupFailure(code::Iceoryx2FFI.iox2_node_cleanup_failure_e)
    return NodeCleanupFailure(code, _error_message(Iceoryx2FFI.iox2_node_cleanup_failure_e, code))
end

function Base.showerror(io::IO, err::NodeCleanupFailure)
    print(io, "NodeCleanupFailure: ", err.message, " (", err.code, ")")
end

struct NodeCreationFailure <: Exception
    code::Iceoryx2FFI.iox2_node_creation_failure_e
    message::String
end

@noinline function NodeCreationFailure(code::Iceoryx2FFI.iox2_node_creation_failure_e)
    return NodeCreationFailure(code, _error_message(Iceoryx2FFI.iox2_node_creation_failure_e, code))
end

function Base.showerror(io::IO, err::NodeCreationFailure)
    print(io, "NodeCreationFailure: ", err.message, " (", err.code, ")")
end

struct NodeListFailure <: Exception
    code::Iceoryx2FFI.iox2_node_list_failure_e
    message::String
end

@noinline function NodeListFailure(code::Iceoryx2FFI.iox2_node_list_failure_e)
    return NodeListFailure(code, _error_message(Iceoryx2FFI.iox2_node_list_failure_e, code))
end

function Base.showerror(io::IO, err::NodeListFailure)
    print(io, "NodeListFailure: ", err.message, " (", err.code, ")")
end

struct NodeWaitFailure <: Exception
    code::Iceoryx2FFI.iox2_node_wait_failure_e
    message::String
end

@noinline function NodeWaitFailure(code::Iceoryx2FFI.iox2_node_wait_failure_e)
    return NodeWaitFailure(code, _error_message(Iceoryx2FFI.iox2_node_wait_failure_e, code))
end

function Base.showerror(io::IO, err::NodeWaitFailure)
    print(io, "NodeWaitFailure: ", err.message, " (", err.code, ")")
end

struct NotifierCreateError <: Exception
    code::Iceoryx2FFI.iox2_notifier_create_error_e
    message::String
end

@noinline function NotifierCreateError(code::Iceoryx2FFI.iox2_notifier_create_error_e)
    return NotifierCreateError(code, _error_message(Iceoryx2FFI.iox2_notifier_create_error_e, code))
end

function Base.showerror(io::IO, err::NotifierCreateError)
    print(io, "NotifierCreateError: ", err.message, " (", err.code, ")")
end

struct NotifierNotifyError <: Exception
    code::Iceoryx2FFI.iox2_notifier_notify_error_e
    message::String
end

@noinline function NotifierNotifyError(code::Iceoryx2FFI.iox2_notifier_notify_error_e)
    return NotifierNotifyError(code, _error_message(Iceoryx2FFI.iox2_notifier_notify_error_e, code))
end

function Base.showerror(io::IO, err::NotifierNotifyError)
    print(io, "NotifierNotifyError: ", err.message, " (", err.code, ")")
end

struct PubSubOpenOrCreateError <: Exception
    code::Iceoryx2FFI.iox2_pub_sub_open_or_create_error_e
    message::String
end

@noinline function PubSubOpenOrCreateError(code::Iceoryx2FFI.iox2_pub_sub_open_or_create_error_e)
    return PubSubOpenOrCreateError(code, _error_message(Iceoryx2FFI.iox2_pub_sub_open_or_create_error_e, code))
end

function Base.showerror(io::IO, err::PubSubOpenOrCreateError)
    print(io, "PubSubOpenOrCreateError: ", err.message, " (", err.code, ")")
end

struct PublisherCreateError <: Exception
    code::Iceoryx2FFI.iox2_publisher_create_error_e
    message::String
end

@noinline function PublisherCreateError(code::Iceoryx2FFI.iox2_publisher_create_error_e)
    return PublisherCreateError(code, _error_message(Iceoryx2FFI.iox2_publisher_create_error_e, code))
end

function Base.showerror(io::IO, err::PublisherCreateError)
    print(io, "PublisherCreateError: ", err.message, " (", err.code, ")")
end

struct ReaderCreateError <: Exception
    code::Iceoryx2FFI.iox2_reader_create_error_e
    message::String
end

@noinline function ReaderCreateError(code::Iceoryx2FFI.iox2_reader_create_error_e)
    return ReaderCreateError(code, _error_message(Iceoryx2FFI.iox2_reader_create_error_e, code))
end

function Base.showerror(io::IO, err::ReaderCreateError)
    print(io, "ReaderCreateError: ", err.message, " (", err.code, ")")
end

struct ReceiveError <: Exception
    code::Iceoryx2FFI.iox2_receive_error_e
    message::String
end

@noinline function ReceiveError(code::Iceoryx2FFI.iox2_receive_error_e)
    return ReceiveError(code, _error_message(Iceoryx2FFI.iox2_receive_error_e, code))
end

function Base.showerror(io::IO, err::ReceiveError)
    print(io, "ReceiveError: ", err.message, " (", err.code, ")")
end

struct RequestResponseOpenOrCreateError <: Exception
    code::Iceoryx2FFI.iox2_request_response_open_or_create_error_e
    message::String
end

@noinline function RequestResponseOpenOrCreateError(code::Iceoryx2FFI.iox2_request_response_open_or_create_error_e)
    return RequestResponseOpenOrCreateError(code, _error_message(Iceoryx2FFI.iox2_request_response_open_or_create_error_e, code))
end

function Base.showerror(io::IO, err::RequestResponseOpenOrCreateError)
    print(io, "RequestResponseOpenOrCreateError: ", err.message, " (", err.code, ")")
end

struct RequestSendError <: Exception
    code::Iceoryx2FFI.iox2_request_send_error_e
    message::String
end

@noinline function RequestSendError(code::Iceoryx2FFI.iox2_request_send_error_e)
    return RequestSendError(code, _error_message(Iceoryx2FFI.iox2_request_send_error_e, code))
end

function Base.showerror(io::IO, err::RequestSendError)
    print(io, "RequestSendError: ", err.message, " (", err.code, ")")
end

struct SemanticStringError <: Exception
    code::Iceoryx2FFI.iox2_semantic_string_error_e
    message::String
end

@noinline function SemanticStringError(code::Iceoryx2FFI.iox2_semantic_string_error_e)
    return SemanticStringError(code, _error_message(Iceoryx2FFI.iox2_semantic_string_error_e, code))
end

function Base.showerror(io::IO, err::SemanticStringError)
    print(io, "SemanticStringError: ", err.message, " (", err.code, ")")
end

struct SendError <: Exception
    code::Iceoryx2FFI.iox2_send_error_e
    message::String
end

@noinline function SendError(code::Iceoryx2FFI.iox2_send_error_e)
    return SendError(code, _error_message(Iceoryx2FFI.iox2_send_error_e, code))
end

function Base.showerror(io::IO, err::SendError)
    print(io, "SendError: ", err.message, " (", err.code, ")")
end

struct ServerCreateError <: Exception
    code::Iceoryx2FFI.iox2_server_create_error_e
    message::String
end

@noinline function ServerCreateError(code::Iceoryx2FFI.iox2_server_create_error_e)
    return ServerCreateError(code, _error_message(Iceoryx2FFI.iox2_server_create_error_e, code))
end

function Base.showerror(io::IO, err::ServerCreateError)
    print(io, "ServerCreateError: ", err.message, " (", err.code, ")")
end

struct ServiceDetailsError <: Exception
    code::Iceoryx2FFI.iox2_service_details_error_e
    message::String
end

@noinline function ServiceDetailsError(code::Iceoryx2FFI.iox2_service_details_error_e)
    return ServiceDetailsError(code, _error_message(Iceoryx2FFI.iox2_service_details_error_e, code))
end

function Base.showerror(io::IO, err::ServiceDetailsError)
    print(io, "ServiceDetailsError: ", err.message, " (", err.code, ")")
end

struct ServiceListError <: Exception
    code::Iceoryx2FFI.iox2_service_list_error_e
    message::String
end

@noinline function ServiceListError(code::Iceoryx2FFI.iox2_service_list_error_e)
    return ServiceListError(code, _error_message(Iceoryx2FFI.iox2_service_list_error_e, code))
end

function Base.showerror(io::IO, err::ServiceListError)
    print(io, "ServiceListError: ", err.message, " (", err.code, ")")
end

struct SubscriberCreateError <: Exception
    code::Iceoryx2FFI.iox2_subscriber_create_error_e
    message::String
end

@noinline function SubscriberCreateError(code::Iceoryx2FFI.iox2_subscriber_create_error_e)
    return SubscriberCreateError(code, _error_message(Iceoryx2FFI.iox2_subscriber_create_error_e, code))
end

function Base.showerror(io::IO, err::SubscriberCreateError)
    print(io, "SubscriberCreateError: ", err.message, " (", err.code, ")")
end

struct TypeDetailError <: Exception
    code::Iceoryx2FFI.iox2_type_detail_error_e
    message::String
end

@noinline function TypeDetailError(code::Iceoryx2FFI.iox2_type_detail_error_e)
    return TypeDetailError(code, _error_message(Iceoryx2FFI.iox2_type_detail_error_e, code))
end

function Base.showerror(io::IO, err::TypeDetailError)
    print(io, "TypeDetailError: ", err.message, " (", err.code, ")")
end

struct WaitsetAttachmentError <: Exception
    code::Iceoryx2FFI.iox2_waitset_attachment_error_e
    message::String
end

@noinline function WaitsetAttachmentError(code::Iceoryx2FFI.iox2_waitset_attachment_error_e)
    return WaitsetAttachmentError(code, _error_message(Iceoryx2FFI.iox2_waitset_attachment_error_e, code))
end

function Base.showerror(io::IO, err::WaitsetAttachmentError)
    print(io, "WaitsetAttachmentError: ", err.message, " (", err.code, ")")
end

struct WaitsetCreateError <: Exception
    code::Iceoryx2FFI.iox2_waitset_create_error_e
    message::String
end

@noinline function WaitsetCreateError(code::Iceoryx2FFI.iox2_waitset_create_error_e)
    return WaitsetCreateError(code, _error_message(Iceoryx2FFI.iox2_waitset_create_error_e, code))
end

function Base.showerror(io::IO, err::WaitsetCreateError)
    print(io, "WaitsetCreateError: ", err.message, " (", err.code, ")")
end

struct WaitsetRunError <: Exception
    code::Iceoryx2FFI.iox2_waitset_run_error_e
    message::String
end

@noinline function WaitsetRunError(code::Iceoryx2FFI.iox2_waitset_run_error_e)
    return WaitsetRunError(code, _error_message(Iceoryx2FFI.iox2_waitset_run_error_e, code))
end

function Base.showerror(io::IO, err::WaitsetRunError)
    print(io, "WaitsetRunError: ", err.message, " (", err.code, ")")
end

struct WriterCreateError <: Exception
    code::Iceoryx2FFI.iox2_writer_create_error_e
    message::String
end

@noinline function WriterCreateError(code::Iceoryx2FFI.iox2_writer_create_error_e)
    return WriterCreateError(code, _error_message(Iceoryx2FFI.iox2_writer_create_error_e, code))
end

function Base.showerror(io::IO, err::WriterCreateError)
    print(io, "WriterCreateError: ", err.message, " (", err.code, ")")
end

@inline function check_ok(code::Cint, ::Type{Iceoryx2FFI.iox2_attribute_definition_error_e})
    if code == _IOX2_OK
        return nothing
    end
    err = Iceoryx2FFI.iox2_attribute_definition_error_e(code)
    throw(AttributeDefinitionError(err))
end

@inline function check_ok(code::Cint, ::Type{Iceoryx2FFI.iox2_attribute_verification_error_e})
    if code == _IOX2_OK
        return nothing
    end
    err = Iceoryx2FFI.iox2_attribute_verification_error_e(code)
    throw(AttributeVerificationError(err))
end

@inline function check_ok(code::Cint, ::Type{Iceoryx2FFI.iox2_blackboard_create_error_e})
    if code == _IOX2_OK
        return nothing
    end
    err = Iceoryx2FFI.iox2_blackboard_create_error_e(code)
    throw(BlackboardCreateError(err))
end

@inline function check_ok(code::Cint, ::Type{Iceoryx2FFI.iox2_blackboard_open_error_e})
    if code == _IOX2_OK
        return nothing
    end
    err = Iceoryx2FFI.iox2_blackboard_open_error_e(code)
    throw(BlackboardOpenError(err))
end

@inline function check_ok(code::Cint, ::Type{Iceoryx2FFI.iox2_client_create_error_e})
    if code == _IOX2_OK
        return nothing
    end
    err = Iceoryx2FFI.iox2_client_create_error_e(code)
    throw(ClientCreateError(err))
end

@inline function check_ok(code::Cint, ::Type{Iceoryx2FFI.iox2_config_creation_error_e})
    if code == _IOX2_OK
        return nothing
    end
    err = Iceoryx2FFI.iox2_config_creation_error_e(code)
    throw(ConfigCreationError(err))
end

@inline function check_ok(code::Cint, ::Type{Iceoryx2FFI.iox2_connection_failure_e})
    if code == _IOX2_OK
        return nothing
    end
    err = Iceoryx2FFI.iox2_connection_failure_e(code)
    throw(ConnectionFailure(err))
end

@inline function check_ok(code::Cint, ::Type{Iceoryx2FFI.iox2_entry_handle_error_e})
    if code == _IOX2_OK
        return nothing
    end
    err = Iceoryx2FFI.iox2_entry_handle_error_e(code)
    throw(EntryHandleError(err))
end

@inline function check_ok(code::Cint, ::Type{Iceoryx2FFI.iox2_entry_handle_mut_error_e})
    if code == _IOX2_OK
        return nothing
    end
    err = Iceoryx2FFI.iox2_entry_handle_mut_error_e(code)
    throw(EntryHandleMutError(err))
end

@inline function check_ok(code::Cint, ::Type{Iceoryx2FFI.iox2_event_open_or_create_error_e})
    if code == _IOX2_OK
        return nothing
    end
    err = Iceoryx2FFI.iox2_event_open_or_create_error_e(code)
    throw(EventOpenOrCreateError(err))
end

@inline function check_ok(code::Cint, ::Type{Iceoryx2FFI.iox2_listener_create_error_e})
    if code == _IOX2_OK
        return nothing
    end
    err = Iceoryx2FFI.iox2_listener_create_error_e(code)
    throw(ListenerCreateError(err))
end

@inline function check_ok(code::Cint, ::Type{Iceoryx2FFI.iox2_listener_wait_error_e})
    if code == _IOX2_OK
        return nothing
    end
    err = Iceoryx2FFI.iox2_listener_wait_error_e(code)
    throw(ListenerWaitError(err))
end

@inline function check_ok(code::Cint, ::Type{Iceoryx2FFI.iox2_loan_error_e})
    if code == _IOX2_OK
        return nothing
    end
    err = Iceoryx2FFI.iox2_loan_error_e(code)
    throw(LoanError(err))
end

@inline function check_ok(code::Cint, ::Type{Iceoryx2FFI.iox2_node_cleanup_failure_e})
    if code == _IOX2_OK
        return nothing
    end
    err = Iceoryx2FFI.iox2_node_cleanup_failure_e(code)
    throw(NodeCleanupFailure(err))
end

@inline function check_ok(code::Cint, ::Type{Iceoryx2FFI.iox2_node_creation_failure_e})
    if code == _IOX2_OK
        return nothing
    end
    err = Iceoryx2FFI.iox2_node_creation_failure_e(code)
    throw(NodeCreationFailure(err))
end

@inline function check_ok(code::Cint, ::Type{Iceoryx2FFI.iox2_node_list_failure_e})
    if code == _IOX2_OK
        return nothing
    end
    err = Iceoryx2FFI.iox2_node_list_failure_e(code)
    throw(NodeListFailure(err))
end

@inline function check_ok(code::Cint, ::Type{Iceoryx2FFI.iox2_node_wait_failure_e})
    if code == _IOX2_OK
        return nothing
    end
    err = Iceoryx2FFI.iox2_node_wait_failure_e(code)
    throw(NodeWaitFailure(err))
end

@inline function check_ok(code::Cint, ::Type{Iceoryx2FFI.iox2_notifier_create_error_e})
    if code == _IOX2_OK
        return nothing
    end
    err = Iceoryx2FFI.iox2_notifier_create_error_e(code)
    throw(NotifierCreateError(err))
end

@inline function check_ok(code::Cint, ::Type{Iceoryx2FFI.iox2_notifier_notify_error_e})
    if code == _IOX2_OK
        return nothing
    end
    err = Iceoryx2FFI.iox2_notifier_notify_error_e(code)
    throw(NotifierNotifyError(err))
end

@inline function check_ok(code::Cint, ::Type{Iceoryx2FFI.iox2_pub_sub_open_or_create_error_e})
    if code == _IOX2_OK
        return nothing
    end
    err = Iceoryx2FFI.iox2_pub_sub_open_or_create_error_e(code)
    throw(PubSubOpenOrCreateError(err))
end

@inline function check_ok(code::Cint, ::Type{Iceoryx2FFI.iox2_publisher_create_error_e})
    if code == _IOX2_OK
        return nothing
    end
    err = Iceoryx2FFI.iox2_publisher_create_error_e(code)
    throw(PublisherCreateError(err))
end

@inline function check_ok(code::Cint, ::Type{Iceoryx2FFI.iox2_reader_create_error_e})
    if code == _IOX2_OK
        return nothing
    end
    err = Iceoryx2FFI.iox2_reader_create_error_e(code)
    throw(ReaderCreateError(err))
end

@inline function check_ok(code::Cint, ::Type{Iceoryx2FFI.iox2_receive_error_e})
    if code == _IOX2_OK
        return nothing
    end
    err = Iceoryx2FFI.iox2_receive_error_e(code)
    throw(ReceiveError(err))
end

@inline function check_ok(code::Cint, ::Type{Iceoryx2FFI.iox2_request_response_open_or_create_error_e})
    if code == _IOX2_OK
        return nothing
    end
    err = Iceoryx2FFI.iox2_request_response_open_or_create_error_e(code)
    throw(RequestResponseOpenOrCreateError(err))
end

@inline function check_ok(code::Cint, ::Type{Iceoryx2FFI.iox2_request_send_error_e})
    if code == _IOX2_OK
        return nothing
    end
    err = Iceoryx2FFI.iox2_request_send_error_e(code)
    throw(RequestSendError(err))
end

@inline function check_ok(code::Cint, ::Type{Iceoryx2FFI.iox2_semantic_string_error_e})
    if code == _IOX2_OK
        return nothing
    end
    err = Iceoryx2FFI.iox2_semantic_string_error_e(code)
    throw(SemanticStringError(err))
end

@inline function check_ok(code::Cint, ::Type{Iceoryx2FFI.iox2_send_error_e})
    if code == _IOX2_OK
        return nothing
    end
    err = Iceoryx2FFI.iox2_send_error_e(code)
    throw(SendError(err))
end

@inline function check_ok(code::Cint, ::Type{Iceoryx2FFI.iox2_server_create_error_e})
    if code == _IOX2_OK
        return nothing
    end
    err = Iceoryx2FFI.iox2_server_create_error_e(code)
    throw(ServerCreateError(err))
end

@inline function check_ok(code::Cint, ::Type{Iceoryx2FFI.iox2_service_details_error_e})
    if code == _IOX2_OK
        return nothing
    end
    err = Iceoryx2FFI.iox2_service_details_error_e(code)
    throw(ServiceDetailsError(err))
end

@inline function check_ok(code::Cint, ::Type{Iceoryx2FFI.iox2_service_list_error_e})
    if code == _IOX2_OK
        return nothing
    end
    err = Iceoryx2FFI.iox2_service_list_error_e(code)
    throw(ServiceListError(err))
end

@inline function check_ok(code::Cint, ::Type{Iceoryx2FFI.iox2_subscriber_create_error_e})
    if code == _IOX2_OK
        return nothing
    end
    err = Iceoryx2FFI.iox2_subscriber_create_error_e(code)
    throw(SubscriberCreateError(err))
end

@inline function check_ok(code::Cint, ::Type{Iceoryx2FFI.iox2_type_detail_error_e})
    if code == _IOX2_OK
        return nothing
    end
    err = Iceoryx2FFI.iox2_type_detail_error_e(code)
    throw(TypeDetailError(err))
end

@inline function check_ok(code::Cint, ::Type{Iceoryx2FFI.iox2_waitset_attachment_error_e})
    if code == _IOX2_OK
        return nothing
    end
    err = Iceoryx2FFI.iox2_waitset_attachment_error_e(code)
    throw(WaitsetAttachmentError(err))
end

@inline function check_ok(code::Cint, ::Type{Iceoryx2FFI.iox2_waitset_create_error_e})
    if code == _IOX2_OK
        return nothing
    end
    err = Iceoryx2FFI.iox2_waitset_create_error_e(code)
    throw(WaitsetCreateError(err))
end

@inline function check_ok(code::Cint, ::Type{Iceoryx2FFI.iox2_waitset_run_error_e})
    if code == _IOX2_OK
        return nothing
    end
    err = Iceoryx2FFI.iox2_waitset_run_error_e(code)
    throw(WaitsetRunError(err))
end

@inline function check_ok(code::Cint, ::Type{Iceoryx2FFI.iox2_writer_create_error_e})
    if code == _IOX2_OK
        return nothing
    end
    err = Iceoryx2FFI.iox2_writer_create_error_e(code)
    throw(WriterCreateError(err))
end

